[tool.poetry]
name = "weatherdata"
version = "0.1.0"
description = ""
authors = ["Alexey Lukyanov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
urllib3 = "1.26.19"
poetry = "1.4.0"
redis = "5.0.7"
numpy = "2.0.0"
plotly = "5.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
